#!/bin/sh

basename=$(basename "$(pwd)")
branch=$(git symbolic-ref --short HEAD)
filepath="$basename-$branch.txt"
dirname=$(dirname "$filepath")
mkdir -p "$dirname"
env >$filepath
echo >&2 "ERROR: dumped ENV in file: $filepath"
exit 1
